/* ============================================================
   CHILDREN / SPONSORSHIP PAGE — CONTENT FILE
   Edit all text here. Save the file. Reload children.html.

   HOW TO ADD A CHILD'S PHOTO:
   Set the "photo" field to the filename, e.g. "photo: 'samuel-k.jpg'"
   Place the photo in the same folder as children.html.
   If no photo is set, initials are shown instead.

   TO ADD MORE CHILDREN: Copy one block, paste after the last
   one (before the closing ] ), change the values.

   TO HIDE A CHILD: Change  active: true  to  active: false
   ============================================================ */

const CHILDREN_CONTENT = {
   
  // ── PAGE TEXT ──────────────────────────────────────────────
  page: {
    heroEyebrow:   "Choose Who You Sponsor",
    heroTitle:     "Every child",
    heroTitleEm:   "has a name.",
    heroBody:      "These are real children in our care — each with a story, a dream, and a deep need for someone like you to stand with them. Choose a child to sponsor and give them the future they deserve.",
    filterAll:     "All Children",
    filterPrimary: "Primary School",
    filterSecondary:"Secondary School",
    filterVocational:"Vocational",
    filterRefugee: "Refugee",
    donateBtn:     "Sponsor This Child",
    donateBtnAlt:  "Give on Behalf of This Child",
    defaultAmount: 30,
    footerNote:    "100% of your sponsorship reaches the child directly. You will receive a personal update and letter from your sponsored child within 60 days.",
  },

  // ── CHILDREN PROFILES ─────────────────────────────────────
  // active: true  = visible on page
  // active: false = hidden (comment in by changing to true)
  children: [

    {
      active: true,
      id: "samuel-k",
      photo: "",                  // e.g. "samuel-k.jpg"
      name: "Samuel Kato",
      age: 13,
      class: "Senior 1 (Grade 7)",
      category: "secondary",
      location: "Kampala, Uganda",
      tag: "Education",
      tagColor: "education",
      story: "Samuel lost both parents to illness when he was 7 years old. He now lives with his elderly grandmother who cannot afford school fees. Despite these hardships, Samuel is consistently top of his class and dreams of becoming an engineer. He needs a sponsor to keep that dream alive.",
      needs: ["School fees & books", "Uniform & shoes", "Daily meals at school"],
      monthlyAmount: 35,
      favoriteSubject: "Mathematics",
      dream: "Electrical Engineer",
    },

    {
      active: true,
      id: "grace-n",
      photo: "",
      name: "Grace Nakato",
      age: 10,
      class: "Primary 5 (Grade 5)",
      category: "primary",
      location: "Wakiso, Uganda",
      tag: "Education",
      tagColor: "education",
      story: "Grace was abandoned by both parents as an infant and raised by a distant relative. She is a bright, curious girl who loves reading and helping younger children with their studies. Without sponsorship she will be forced to drop out at the end of this term.",
      needs: ["School fees", "Books & stationery", "School uniform"],
      monthlyAmount: 30,
      favoriteSubject: "English & Reading",
      dream: "Schoolteacher",
    },

    {
      active: true,
      id: "grace-n",
      photo: "",
      name: "Grace Nakato",
      age: 10,
      class: "Primary 5 (Grade 5)",
      category: "primary",
      location: "Wakiso, Uganda",
      tag: "Education",
      tagColor: "education",
      story: "Grace was abandoned by both parents as an infant and raised by a distant relative. She is a bright, curious girl who loves reading and helping younger children with their studies. Without sponsorship she will be forced to drop out at the end of this term.",
      needs: ["School fees", "Books & stationery", "School uniform"],
      monthlyAmount: 30,
      favoriteSubject: "English & Reading",
      dream: "Schoolteacher",
    },
     {
      active: true,
      id: "david-m",
      photo: "",
      name: "David Mugisha",
      age: 16,
      class: "Senior 3 (Grade 9)",
      category: "secondary",
      location: "Mbarara, Uganda",
      tag: "Education",
      tagColor: "education",
      story: "David's father died in a road accident and his mother remarried, leaving him in the care of a church elder. He is determined and hardworking but faces expulsion over unpaid school fees. He scored top marks in his national exams and was recommended for a science track.",
      needs: ["Secondary school fees", "Science lab equipment", "Boarding fees"],
      monthlyAmount: 45,
      favoriteSubject: "Biology & Chemistry",
      dream: "Medical Doctor",
    },

    {
      active: true,
      id: "esther-a",
      photo: "",
      name: "Esther Apolot",
      age: 18,
      class: "Vocational — Tailoring",
      category: "vocational",
      location: "Soroti, Uganda",
      tag: "Vocational",
      tagColor: "vocational",
      story: "Esther dropped out of school at 14 when her parents died within months of each other. She is now enrolled in HFM's vocational tailoring programme and shows extraordinary talent. Completing this programme would allow her to open her own business and support her two younger siblings.",
      needs: ["Programme fees", "Sewing materials", "Business startup grant"],
      monthlyAmount: 40,
      favoriteSubject: "Fashion Design",
      dream: "Fashion Designer & Shop Owner",
    },

    {
      active: true,
      id: "john-o",
      photo: "",
      name: "John Okello",
      age: 9,
      class: "Primary 3 (Grade 3)",
      category: "primary",
      location: "Gulu, Uganda",
      tag: "Education",
      tagColor: "education",
      story: "John is a refugee child who fled South Sudan with his aunt after losing his parents to conflict. He arrived in Uganda with no documentation and no school access. HFM enrolled him in a catchup programme and he is now flourishing. He is playful, kind, and loves football.",
      needs: ["School fees", "Meals", "Shoes & clothing", "Medical care"],
      monthlyAmount: 30,
      favoriteSubject: "Sports & Physical Education",
      dream: "Football Player",
      isRefugee: true,
      category: "refugee",
      tag: "Refugee",
      tagColor: "refugee",
    },

    {
      active: true,
      id: "mary-k",
      photo: "",
      name: "Mary Kyomugisha",
      age: 14,
      class: "Senior 2 (Grade 8)",
      category: "secondary",
      location: "Kabale, Uganda",
      tag: "Education",
      tagColor: "education",
      story: "Mary is the oldest of five orphaned siblings, all being raised by their 72-year-old grandfather. She carries enormous family responsibility but refuses to let it extinguish her ambition. Her teachers say she is the most determined student they have seen in years.",
      needs: ["School fees", "School supplies", "Sanitary supplies"],
      monthlyAmount: 35,
      favoriteSubject: "History & Social Studies",
      dream: "Lawyer or Politician",
    },

    {
      active: true,
      id: "peter-w",
      photo: "",
      name: "Peter Wasswa",
      age: 11,
      class: "Primary 6 (Grade 6)",
      category: "primary",
      location: "Jinja, Uganda",
      tag: "Education",
      tagColor: "education",
      story: "Peter and his twin brother both lost their mother in childbirth and their father disappeared when they were toddlers. An HFM partner church placed them with a caring family. Peter has shown remarkable aptitude in mathematics and has already been identified as gifted.",
      needs: ["School fees", "Books & uniform", "Extra tutoring support"],
      monthlyAmount: 30,
      favoriteSubject: "Mathematics",
      dream: "Accountant",
    },

    {
      active: true,
      id: "hope-m",
      photo: "",
      name: "Hope Mirembe",
      age: 7,
      class: "Primary 1 (Grade 1)",
      category: "primary",
      location: "Masaka, Uganda",
      tag: "Education",
      tagColor: "education",
      story: "Hope's name tells her story — she is a joy to everyone around her. Born to a teenage mother who could not care for her, she was placed with HFM's family support programme. At 7 she is starting school for the first time and approaches every lesson with infectious excitement.",
      needs: ["First-year school fees", "School bag & supplies", "Nutritional meals"],
      monthlyAmount: 28,
      favoriteSubject: "Drawing & Art",
      dream: "Artist",
    },

    {
      active: true,
      id: "isaac-b",
      photo: "",
      name: "Isaac Byamukama",
      age: 17,
      class: "Senior 4 (Grade 10)",
      category: "secondary",
      location: "Fort Portal, Uganda",
      tag: "Education",
      tagColor: "education",
      story: "Isaac survived a period of life on the streets after both parents died of HIV-related illness. He was identified by HFM's outreach team, enrolled in school, and has never looked back. He is preparing for his Uganda Certificate of Education exams and needs support to complete this critical year.",
      needs: ["Exam fees", "Boarding accommodation", "Revision books"],
      monthlyAmount: 50,
      favoriteSubject: "Physics & Technology",
      dream: "Software Developer",
    },

    {
      active: true,
      id: "ruth-a",
      photo: "",
      name: "Ruth Amoding",
      age: 15,
      class: "Vocational — Catering",
      category: "vocational",
      location: "Lira, Uganda",
      tag: "Vocational",
      tagColor: "vocational",
      story: "Ruth is a refugee from the DRC who has shown a passion for cooking and nutrition. After completing HFM's catering programme she hopes to start a small canteen business near the settlement that will employ other women and provide healthy food for the community.",
      needs: ["Catering programme fees", "Cooking equipment", "Business startup support"],
      monthlyAmount: 40,
      favoriteSubject: "Cookery & Nutrition",
      dream: "Restaurateur",
      isRefugee: true,
      category: "refugee",
      tag: "Refugee",
      tagColor: "refugee",
    },

    // ── The following 10 children are commented out ──────────
    // To show them: change  active: false  to  active: true

    {
      active: false,
      id: "james-n",
      photo: "",
      name: "James Nsubuga",
      age: 12,
      class: "Primary 7 (Grade 7)",
      category: "primary",
      location: "Entebbe, Uganda",
      tag: "Education",
      tagColor: "education",
      story: "James is the son of a single mother who died of cancer last year. He was placed with an aunt who struggles financially. A natural leader and class monitor, James organises younger students and mediates conflicts — his teachers say he has the heart of a pastor.",
      needs: ["School fees", "Books", "Meals"],
      monthlyAmount: 30,
      favoriteSubject: "Social Studies",
      dream: "Pastor or Counsellor",
    },

    {
      active: false,
      id: "lydia-k",
      photo: "",
      name: "Lydia Kemigisha",
      age: 16,
      class: "Senior 3 (Grade 9)",
      category: "secondary",
      location: "Kampala, Uganda",
      tag: "Education",
      tagColor: "education",
      story: "Lydia's parents separated when she was 3, and neither took responsibility for her upbringing. She was raised in a children's home until HFM's family reintegration programme placed her with a caring aunt. She is a gifted writer and has been published in a local school magazine.",
      needs: ["Secondary fees", "Writing materials", "Career guidance"],
      monthlyAmount: 38,
      favoriteSubject: "English Literature",
      dream: "Journalist or Author",
    },

    {
      active: false,
      id: "timothy-o",
      photo: "",
      name: "Timothy Okwir",
      age: 8,
      class: "Primary 2 (Grade 2)",
      category: "primary",
      location: "Kitgum, Uganda",
      tag: "Education",
      tagColor: "education",
      story: "Timothy was found malnourished by HFM's outreach team during a community visit. His mother had died and his father was in prison. After receiving medical care and nutrition support, he began school for the first time. He is now healthy, smiling, and learning to read.",
      needs: ["School fees", "Medical follow-ups", "Food & nutrition"],
      monthlyAmount: 28,
      favoriteSubject: "Music",
      dream: "Singer",
    },

    {
      active: false,
      id: "sarah-m",
      photo: "",
      name: "Sarah Mutesi",
      age: 19,
      class: "Vocational — ICT",
      category: "vocational",
      location: "Kampala, Uganda",
      tag: "Vocational",
      tagColor: "vocational",
      story: "Sarah was orphaned at 13 and spent two years out of school. Identified by HFM's community team, she was enrolled in our ICT vocational programme and has since become the top student in her cohort. She is building a website for a local business as part of her final project.",
      needs: ["Programme completion fees", "Laptop access", "Internship placement"],
      monthlyAmount: 45,
      favoriteSubject: "Web Design & Programming",
      dream: "Software Engineer",
    },

    {
      active: false,
      id: "daniel-a",
      photo: "",
      name: "Daniel Achola",
      age: 14,
      class: "Senior 2 (Grade 8)",
      category: "refugee",
      location: "Bidibidi Settlement, Uganda",
      tag: "Refugee",
      tagColor: "refugee",
      story: "Daniel fled South Sudan with his younger sister after their parents were killed in conflict. He is her sole guardian at 14. Despite this enormous weight, he attends school every day without fail and refuses to let his sister see him break. He is extraordinarily brave.",
      needs: ["School fees for both siblings", "Food & shelter support", "Trauma counselling"],
      monthlyAmount: 50,
      favoriteSubject: "History",
      dream: "Peacemaker — UN Worker",
      isRefugee: true,
    },

    {
      active: true,
      id: "faith-n",
      photo: "",
      name: "Faith Namazzi",
      age: 10,
      class: "Primary 4 (Grade 4)",
      category: "primary",
      location: "Mukono, Uganda",
      tag: "Education",
      tagColor: "education",
      story: "Faith has a rare gift for languages — she already speaks Luganda, Swahili, and is learning English rapidly. Her mother died in childbirth and her father works as a subsistence farmer who cannot afford school fees. Faith's teachers believe she is one of the most linguistically gifted children they have taught.",
      needs: ["School fees", "Language learning resources", "Meals"],
      monthlyAmount: 30,
      favoriteSubject: "Languages",
      dream: "Diplomat or Translator",
    },

    {
      active: false,
      id: "charles-b",
      photo: "",
      name: "Charles Byabagabo",
      age: 17,
      class: "Senior 4 (Grade 10)",
      category: "secondary",
      location: "Rukungiri, Uganda",
      tag: "Education",
      tagColor: "education",
      story: "Charles's mother is chronically ill and his father died when he was 5. He works on a neighbour's farm before and after school to help feed his mother, yet still maintains above-average grades. He is preparing for his national exams and dreams of a university scholarship.",
      needs: ["Exam registration fees", "Revision materials", "Nutrition support for mother"],
      monthlyAmount: 45,
      favoriteSubject: "Agriculture & Science",
      dream: "Agricultural Scientist",
    },

    {
      active: false,
      id: "anna-k",
      photo: "",
      name: "Anna Kobusinge",
      age: 9,
      class: "Primary 3 (Grade 3)",
      category: "primary",
      location: "Kasese, Uganda",
      tag: "Education",
      tagColor: "education",
      story: "Anna was rescued from a child labour situation at the age of 7 and placed in HFM's care. She had never attended school. Now 9, she has caught up to her peers and is described by her teacher as having 'a fire to learn that burns brighter every single day.'",
      needs: ["School fees", "Psychosocial support", "Clothing & hygiene supplies"],
      monthlyAmount: 30,
      favoriteSubject: "Science",
      dream: "Nurse",
    },

    {
      active: false,
      id: "philip-w",
      photo: "",
      name: "Philip Wanyama",
      age: 13,
      class: "Primary 7 (Grade 7)",
      category: "primary",
      location: "Tororo, Uganda",
      tag: "Education",
      tagColor: "education",
      story: "Philip is deaf in one ear following a childhood illness that went untreated. His grandmother, who is raising him, cannot afford the hearing aid he needs. Despite this challenge, Philip is a diligent student who communicates remarkably well and refuses to let his disability define him.",
      needs: ["School fees", "Hearing aid device", "Medical follow-up care"],
      monthlyAmount: 35,
      favoriteSubject: "Art & Technical Drawing",
      dream: "Architect",
    },

    {
      active: false,
      id: "joy-a",
      photo: "",
      name: "Joy Acan",
      age: 20,
      class: "Vocational — Hair & Beauty",
      category: "vocational",
      location: "Arua, Uganda",
      tag: "Vocational",
      tagColor: "vocational",
      story: "Joy grew up in the Rhino Camp refugee settlement. Sponsored by HFM since age 12, she completed secondary school and is now in her final term of a professional hair and beauty course. She is about to open her first salon chair inside the settlement — creating employment and dignity for other women.",
      needs: ["Final programme payment", "Salon equipment grant", "Business registration"],
      monthlyAmount: 40,
      favoriteSubject: "Beauty Therapy",
      dream: "Salon Owner & Trainer",
      isRefugee: true,
      category: "refugee",
      tag: "Refugee",
      tagColor: "refugee",
    },

  ], // end children array

}; // end CHILDREN_CONTENT
